# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"(\n\x07\x44\x61taMap\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\x01\"\x99\x01\n\x0fModelParameters\x12\x1f\n\x17\x63hangepoint_prior_scale\x18\x01 \x01(\x01\x12\x1f\n\x17seasonality_prior_scale\x18\x02 \x01(\x01\x12\x18\n\x10seasonality_mode\x18\x03 \x01(\t\x12\x1a\n\x12yearly_seasonality\x18\x04 \x01(\x08\x12\x0e\n\x06growth\x18\x05 \x01(\t\"v\n\x04\x44\x61ta\x12\x16\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x08.DataMap\x12\x0f\n\x07periods\x18\x02 \x01(\x05\x12*\n\x10model_parameters\x18\x03 \x01(\x0b\x32\x10.ModelParameters\x12\x19\n\x11return_components\x18\x04 \x01(\x08\"#\n\x11\x46orecastComponent\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\xed\x01\n\x08\x46orecast\x12\x16\n\x0e\x66orecast_dates\x18\x01 \x03(\t\x12\x17\n\x0f\x66orecast_values\x18\x02 \x03(\x01\x12\x1c\n\x14\x66orecast_lower_bound\x18\x03 \x03(\x01\x12\x1c\n\x14\x66orecast_upper_bound\x18\x04 \x03(\x01\x12-\n\ncomponents\x18\x05 \x03(\x0b\x32\x19.Forecast.ComponentsEntry\x1a\x45\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ForecastComponent:\x02\x38\x01\"7\n\x0f\x46orecastRequest\x12\x13\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x05.Data\x12\x0f\n\x07\x61pi_url\x18\x02 \x01(\t\"8\n\x14SaveForecastResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x13SaveForecastRequest\x12\x1b\n\x08\x66orecast\x18\x01 \x01(\x0b\x32\t.Forecast\x12\x13\n\x0boutput_path\x18\x02 \x01(\t2@\n\x12GetForecastService\x12*\n\x0bGetForecast\x12\x10.ForecastRequest\x1a\t.Forecast2R\n\x13SaveForecastService\x12;\n\x0cSaveForecast\x12\x14.SaveForecastRequest\x1a\x15.SaveForecastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECAST_COMPONENTSENTRY']._loaded_options = None
  _globals['_FORECAST_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_DATAMAP']._serialized_start=17
  _globals['_DATAMAP']._serialized_end=57
  _globals['_MODELPARAMETERS']._serialized_start=60
  _globals['_MODELPARAMETERS']._serialized_end=213
  _globals['_DATA']._serialized_start=215
  _globals['_DATA']._serialized_end=333
  _globals['_FORECASTCOMPONENT']._serialized_start=335
  _globals['_FORECASTCOMPONENT']._serialized_end=370
  _globals['_FORECAST']._serialized_start=373
  _globals['_FORECAST']._serialized_end=610
  _globals['_FORECAST_COMPONENTSENTRY']._serialized_start=541
  _globals['_FORECAST_COMPONENTSENTRY']._serialized_end=610
  _globals['_FORECASTREQUEST']._serialized_start=612
  _globals['_FORECASTREQUEST']._serialized_end=667
  _globals['_SAVEFORECASTRESPONSE']._serialized_start=669
  _globals['_SAVEFORECASTRESPONSE']._serialized_end=725
  _globals['_SAVEFORECASTREQUEST']._serialized_start=727
  _globals['_SAVEFORECASTREQUEST']._serialized_end=798
  _globals['_GETFORECASTSERVICE']._serialized_start=800
  _globals['_GETFORECASTSERVICE']._serialized_end=864
  _globals['_SAVEFORECASTSERVICE']._serialized_start=866
  _globals['_SAVEFORECASTSERVICE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
